name: lint

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PNPM
        run: npm i -g pnpm

      # # - name: Setup pnpm
      # #   uses: pnpm/action-setup@v4
      # #   with:
      # #     version: 9   # la versión de pnpm que usas localmente
      # #     run_install: false

      # - name: Install deps (locked)
      #   run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint